In [2]:
### NAMA    : Stevando Christian Hesha
### NIM     : 225314181

In [9]:
# 1. Membuat List
# 1.1. Dapatkah sebuah list berisi data yang memilliki tipe data yang berbeda ?
# 1.2. Buatlah sebuah list dengan nama "mylist" berisi "0",1,"two", 2,3,4
mylist = ["0", 1, "two", 2, 3, 4]
# 1.3. Tampilkan isi mylist
print("My List")
print(mylist)
print()
# 1.4. Apakah terjadi error ?
print("Apakah terjadi error ?")
print("Tidak")
print()
# 1.5. Mengapa ?
# Karena pada saat penulisan elemen dipisahkan dengan koma dan saat memulai serta menutup diakhiri tanda petik dua

My List
['0', 1, 'two', 2, 3, 4]

Apakah terjadi error ?
Tidak

Mengapa ?
Karena pada saat penulisan elemen dipisahkan dengan koma dan saat memulai serta menutup diakhiri tanda petik dua


In [16]:
# 2. Mencetak isi list
# 2.1. Tampilkan setiap element dari mylist
print("Setiap elemen dari mylist")
for element in mylist:
    print(element)
print()
# 2.2. Tampilkan isi mylist index ke-3 
print("Isi mylist index ke-3 ")
print(mylist[3])


Setiap elemen dari mylist
0
1
two
2
3
4

Isi mylist index ke-3 
2


In [21]:
#3.0. Kesepakatan programmer Pyhton, Numpy biasanya disingkat np. Selanjutnya gunakan np
## import numpy as np
import numpy as np

#3.1. Ubahlah  mylist kedalam numpy array beri nama myarray
myarray = np.array(mylist)

#3.2. Tampilkan isi myarray
print("Isi myarray")
print(myarray)
print()

#3.3. Buatlah array menggunakan numpy array berisi nilai : 10,11,12,13,14 beri nama myarray2
myarray2 = np.array([10, 11, 12, 13, 14])

#3.4. Tampilkan isi setiap elemen dari myarray2. Tampilan yang diinginkan : [10 11 12 13 14]
print("Isi myarray2")
print(myarray2)
print()

#3.5. Tampilkan isi myarray2 lagi, tampilan yang diinginkan : Tampilan yang diinginkan (tanpa # tidak ditampilkan)
 #      myarray[0]=10
  #     myarray[1]=11
   #    myarray[2]=12
    #   myarray[3]=13
     #  myarray[4]=14
print("# myarray2")
print(myarray2)

for i in range(len(myarray2)):
  print(f"      myarray[{i}]={myarray2[i]}")
print()

#3.6. Tampilkan elemen dari myarray2 index ke-3 yaitu (13).
print("Elemen dari myarray2 index ke-3 adalah ")
print(myarray2[3])


Isi myarray
['0' '1' 'two' '2' '3' '4']

Isi myarray2
[10 11 12 13 14]

# myarray2
[10 11 12 13 14]
      myarray[0]=10
      myarray[1]=11
      myarray[2]=12
      myarray[3]=13
      myarray[4]=14

Elemen dari myarray2 index ke-3 adalah 
13


In [24]:
# 4.1. Buatlah sebuah list dengan nama mylist2 berisi 10,11,12,13,14
mylist2 = [10,11,12,13,14]

# 4.2. Kalikan mylist2 dengan 3  
print(mylist2 * 3)

# 4.3. Kalikan myarray2 dengan 3 (myarray2 ada pada bagian 3.3)
print(myarray2 * 3)

# 4.4. Apa perbedaan anatara 4.2 dan 4.3. Jelaskan secara singkat
# Perbedaan terdapat pada tipe datanya. 
# Pada mylist2 bertipe list python dan pada myarray2 bertipe numpy array")
# Perbedaan pada operasi perkaliannya

[10, 11, 12, 13, 14, 10, 11, 12, 13, 14, 10, 11, 12, 13, 14]
[30 33 36 39 42]


In [27]:
#5.1. buatlah array yang berisi nilai 0 (gunakan fungsi zeros) 
### sebanyak 7 beri nama arrayzeros, tampilkan hasilnya
import numpy as np

arrayzeros = np.zeros(7)

print(arrayzeros)
print()

#5.2. buatlah array yang berisi nilai 1 (gunakan fungsi ones) 
### sebanyak 7 beri nama arrayones, tampilkan hasilnya
arrayones = np.ones(7)

print(arrayones)
print()

#5.3. buatlah array dimulai dari 10 sd 50 step 5 (gunakan fungsi arange) 
### beri nama arrayarange tampilkan hasilnya
arrayarange = np.arange(10, 50, 5)

print(arrayarange)
print()

#5.4. buatlah array dimulai dari 10 sd 101 step 10 (gunakan fungsi arange) 
### beri nama arrayarange tampilkan hasilnya
arrayarange = np.arange(10, 101, 10)

print(arrayarange)
print()

#5.5. buatlah array dimulai dari 10 sd 100 sejumlah 10 (gunakan fungsi linspace) 
### beri nama arrayalinspace tampilkan hasilnya
arraylinspace = np.linspace(10, 100, 10)

print(arraylinspace)
print()

#5.6. Berikan penjelasan perbedaan antara 5.4 dan 5.5.
# pada 

[0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1. 1. 1. 1. 1.]

[10 15 20 25 30 35 40 45]

[ 10  20  30  40  50  60  70  80  90 100]

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]



In [29]:
# 6.1. Tampilkan tipe dari myarray2
print(type(myarray2))

# 6.2. Tampilkan tipe dari data yang ada dalam myarray2
print(myarray2.dtype)

# 6.3. Apa perbedaan antara 6.1 dan 6.2
# pada 6.1 akan menampilkan tipe data dari myarray2 
# sedangkan 6.2 akan menampilkan tipe data yang ada didalam myarray 2

<class 'numpy.ndarray'>
int32


In [33]:
#7.1. Buatlah array 2 dimensi, beri nama arrku. Isi arrku adalah :
## baris 1 : [11,12,13,14,15], baris 2 =[21,22,23,24,25], baris 3 =[31, 32, 33,34,35]
import numpy as np

arrku = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
])

#7.2. Tampilkan arrku
print("arrku")
print(arrku)
print()

#7.3. Tampilkan jumlah elemen dari arrku (size)
print("jumlah arrku")
print(arrku.size)
print()

#7.4. Tampilkan  dimensi dari arrku (ndim)
print("Dimensi arrku")
print(arrku.ndim)
print()

#7.5. Tampilkan ukuran dari arrku (shape)  
print("Ukuran arrku")
print(arrku.shape)
print()

#7.6. Tampilkan transpose dari arrku (T)
print("Transpose dari arrku")
print(arrku.T)
print()


arrku
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]

jumlah arrku
15

Dimensi arrku
2

Ukuran arrku
(3, 5)

Transpose dari arrku
[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]
 [15 25 35]]



In [35]:
# 8. Indexing dan Slicing Array
# 8.1. Tampilkan element arrku dari baris kedua dan kolom kelima (hasil : 25)
print(arrku[1, 4])


25


In [36]:
# 8.2. Tampilkan element arrku dari tiga kolom pertama dari baris pertama ([11 12 13])
print(arrku[0, :3])


[11 12 13]


In [37]:
# 8.3. Tampilkan element arrku dari baris pertama dan kedua dan kolom ketiga ([13,23])
print(arrku[0:2, 2])


[13 23]


In [38]:
# 8.4. Tampilkan element arrku dari baris pertama dan kedua ([[11, 12, 13, 14, 15],[21, 22, 23, 24, 25]])
print(arrku[0:2, :])


[[11 12 13 14 15]
 [21 22 23 24 25]]


In [40]:
# 8.4. Perintah untuk menghasilkan element arrku dari kolom kelima seperti berikut (abaikan ##): 
## array([15],
##       [25],
##       [35])
print(arrku[:, 4].reshape(-1, 1))


[[15]
 [25]
 [35]]


In [43]:
#9.1. Buatlah : arr_A = np.array([11,12,13,14,15])
arr_A = np.array([11, 12, 13, 14, 15])

#9.2. Buatlah : arr_B = np.array([2,2,2,2,2])
arr_B = np.array([2, 2, 2, 2, 2])

#9.3. Lakukan operasi penjualan arry_A dan arry_B. Hasil yang diinginkan
#Penjumlahan =  [13 14 15 16 17]
penjumlahan = arr_A + arr_B

#9.4. Lakukan operasi pengurangan arry_A dan arry_B. Hasil yang diinginkan
#Pengurangan =  [9 10 11 12 13]
pengurangan = arr_A - arr_B

#9.5. Lakukan operasi perkalian arry_A dan arry_B. Hasil yang diinginkan
#Perkalian =  [22 24 26 28 30]
perkalian = arr_A * arr_B

#9.6. Lakukan operasi pembagian arry_A dan arry_B. Hasil yang diinginkan
#Pembagian =  [5.5 6.  6.5 7.  7.5]
pembagian = arr_A / arr_B

#9.7. Lakukan operasi perpangkatan : arry_A dipangkatkan arry_B. Hasil yang diinginkan
#Perpangkatan =  [121 144 169 196 225]
perpangkatan = arr_A ** arr_B

#9.8. Lakukan operasi perkalian dot product arry_A dan arry_B. Hasil yang diinginkan
#Perkalian Dot =  130
perkalian_dot = np.dot(arr_A, arr_B)

# Menampilkan hasil
print("Penjumlahan:", penjumlahan)
print("Pengurangan:", pengurangan)
print("Perkalian:", perkalian)
print("Pembagian:", pembagian)
print("Perpangkatan:", perpangkatan)
print("Perkalian Dot:", perkalian_dot)

#9.9. Tampilkan / cetak isi dari arrku, hasil yang diinginkan (abaikan #)
#[[11 12 13 14 15]
# [21 22 23 24 25]
# [31 32 33 34 35]]
print(arrku)

#9.10 tampilkan nilai minimum dari arrku
minimum = arrku.min()
#9.11 tampilkan nilai maksimum dari arrku
maksimum = arrku.max()
#9.12 tampilkan nilai rata-rata dari arrku
rata_rata = arrku.mean()
#9.13 tampilkan nilai total dari arrku
total = arrku.sum()
#9.14 tampilkan nilai standar deviasi dari arrku
standar_deviasi = arrku.std()
#9.15 tampilkan index nilai minimum
index_minimum = arrku.argmin()
#9.16 tampilkan index nilai maksimum
index_maksimum = arrku.argmax()
## Hasil yang diinginkan dari 9.10 sd 9.16 adalah (abaikan #)
#Nilai minimal =  11
#Nilai maksimal =  35
#Nilai rata-rata =  23.0
#Total nilai =  345
#Standar Deviasi =  8.286535263104035
#Index nilai minimum =  0
#Index nilai maksimum =  14

# Menampilkan hasil
print("Nilai minimal:", minimum)
print("Nilai maksimal:", maksimum)
print("Nilai rata-rata:", rata_rata)
print("Total nilai:", total)
print("Standar Deviasi:", standar_deviasi)
print("Index nilai minimum:", index_minimum)
print("Index nilai maksimum:", index_maksimum)

Penjumlahan: [13 14 15 16 17]
Pengurangan: [ 9 10 11 12 13]
Perkalian: [22 24 26 28 30]
Pembagian: [5.5 6.  6.5 7.  7.5]
Perpangkatan: [121 144 169 196 225]
Perkalian Dot: 130
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]]
Nilai minimal: 11
Nilai maksimal: 35
Nilai rata-rata: 23.0
Total nilai: 345
Standar Deviasi: 8.286535263104035
Index nilai minimum: 0
Index nilai maksimum: 14


In [45]:
## 10.1 Buatlah array : arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

## 10.2. Ubah arr dengan ukuran 4x3 
#[[ 1  2  3]
# [ 4  5  6]
# [ 7  8  9]
# [10 11 12]]
arr = arr.reshape(4, 3)

print(arr)


## 10.3. Lakukan reshape arr menjadi array 3 dimensi 

##[[[ 1  2]
#  [ 3  4]
#  [ 5  6]]

##[[ 7  8]
#  [ 9 10]
#  [11 12]]]

arr = arr.reshape(3, 3, 2)

print(arr)

## 10.4. Lakukan reshape dengan ukuran array diserahkan kepada python
#[[[ 1  2  3]
#  [ 4  5  6]]

# [[ 7  8  9]
#  [10 11 12]]]

arr = arr.reshape(-1, 2, 3)

print(arr)

## 10.5 Lakukan proses flattening array dari arrku
#[11 12 13 14 15 21 22 23 24 25 31 32 33 34 35]

arrku_flat = arrku.flatten()

print(arrku_flat)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


ValueError: cannot reshape array of size 12 into shape (3,3,2)